# Notes DynamoDB Table
NotesTable:
  Type: AWS::DynamoDB::Table # Resource type
  Properties:
    TableName: notes
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions: # Required list of attribute definitions
      - AttributeName: notesId # Required attribute name for the table’s primary key
        AttributeType: S # (S | N | B) for string, number, binary
    KeySchema: # Required list of hash and range attributes
      - AttributeName: notesId
        KeyType: HASH

# Cognitive User Pool
CognitoUserPool: #logical name
  Type: AWS::Cognito::UserPool
  Properties:
    UserPoolName: MyNotesUP

# User Pool Web Client
CognitoUserPoolWebClient:
  Type: AWS::Cognito::UserPoolClient
  Properties:
    UserPoolId: !Ref CognitoUserPool # !Ref is a function that returns the value of the specified parameter or resource
    ClientName: web
    AllowedOAuthFlows:
      - implicit
    CallbackURLs:
      - http://localhost:3000
    AllowedOAuthFlowsUserPoolClient: true
    SupportedIdentityProviders:
      - COGNITO
    AllowedOAuthScopes:
      - email
      - openid
      - profile
      - phone

# User Pool domain
CognitoUserPoolDomain:
  Type: AWS::Cognito::UserPoolDomain
  Properties:
    UserPoolId: !Ref CognitoUserPool
    Domain: mynotescd2222

# Application Parameters
userPoolIdParam:
  Type: AWS::SSM::Parameter
  Properties:
    Name: /notes/dev/userPoolArn
    Type: String
    Value: !GetAtt CognitoUserPool.Arn
