service: notes-api-v3 # Name of your serverless service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'} # Set the default stage to dev
  region: us-east-1

functions:
  authorizer:
    handler: authorizer.handlerV2

  createNote:
    handler: handler.createNote
    environment:
      NOTES_TABLE_NAME: !Ref NotesTable # Get the physical name of the table resource, format: NotesTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1 # Enable connection reuse for AWS SDK for JavaScript
    iamRoleStatements: # IAM role statements for the Lambda function
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: !GetAtt NotesTable.Arn # Get the ARN of the table resource, format: arn:aws:dynamodb:us-east-1:123456789012:table/NotesTable
    events:
      - http:
          method: post
          path: notes
          authorizer: authorizer # Use the authorizer function

  updateNote:
    handler: handler.updateNote
    environment:
      NOTES_TABLE_NAME: !Ref NotesTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: !GetAtt NotesTable.Arn
    events:
      - http:
          method: put
          path: notes/{id}
          authorizer: authorizer # Use the authorizer function

  deleteNote:
    handler: handler.deleteNote
    environment:
      NOTES_TABLE_NAME: !Ref NotesTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource: !GetAtt NotesTable.Arn
    events:
      - http:
          method: delete
          path: notes/{id}
          authorizer: authorizer # Use the authorizer function

  getNote:
    handler: handler.getNote
    environment:
      NOTES_TABLE_NAME: !Ref NotesTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
        Resource: !GetAtt NotesTable.Arn
    events:
      - http:
          method: get
          path: notes/{id}
          authorizer: authorizer # Use the authorizer function

  getAllNote:
    handler: handler.getAllNote
    environment:
      NOTES_TABLE_NAME: !Ref NotesTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Scan
        Resource: !GetAtt NotesTable.Arn
    events:
      - http:
          method: get
          path: notes/
          authorizer:
            name: userpool_authorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn

plugins:
  - serverless-iam-roles-per-function
  - serverless-plugin-typescript

resources:
  Resources: ${file(resources.yml)} # Include the resources.yml file
