service: notes-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1

functions:
  createNote:
    handler: handler.createNote
    events:
      - http:
          method: post
          path: notes
  updateNote:
    handler: handler.updateNote
    events:
      - http:
          method: put
          path: notes/{id}
  deleteNote:
    handler: handler.deleteNote
    events:
      - http:
          method: delete
          path: notes/{id}
  getNote:
    handler: handler.getNote
    events:
      - http:
          method: get
          path: notes/{id}
  getAllNote:
    handler: handler.getAllNote
    events:
      - http:
          method: get
          path: notes/
