service: notes-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1

functions:
  createNote:
    handler: handler.createNote
    events:
      - http:
          method: post
          path: notes
